name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run JSX Syntax Validation
        run: npm run jsx:check

      - name: Run JSX ESLint Validation
        run: npm run lint:tsx

      - name: Run TypeScript type-check
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: npm test -- --coverage --passWithNoTests --watchAll=false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          allow-licenses: BSD-2-Clause, BSD-3-Clause, MIT, Apache-2.0, ISC
          deny-licenses: MS-PL, BSD, JSON

  lint-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run commit linting
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
          failOnWarnings: false

  coverage-threshold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage threshold
        run: npm test -- --coverage --coverageReporters=text --watchAll=false
        env:
          CI: true

      - name: Check coverage threshold (60%)
        run: |
          COVERAGE=$(grep 'All files' coverage/coverage.txt | grep -oE '[0-9]+\.[0-9]+' | head -1)
          if (( $(echo "$COVERAGE < 60.0" | bc -l) )); then
            echo "Coverage $COVERAGE% is below 60% threshold"
            exit 1
          else
            echo "Coverage $COVERAGE% meets 60% threshold ✓"
          fi
