name: PR Guard (forbidden paths)

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect forbidden path changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            forbidden:
              - ".github/**"
              - "**/*.env"
              - ".env*"
              - "**/secrets/**"

      - name: Enforce maintainer override for forbidden changes
        if: steps.filter.outputs.forbidden == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels?.map(l => l.name) ?? [];
            const actor = context.actor;
            const allowedActors = ['pixel-pilot']; // repo owner/maintainer
            const hasOverride = labels.includes('maintainer-override');
            if (hasOverride || allowedActors.includes(actor)) {
              core.notice('Forbidden paths changed but maintainer override present or actor allowed.');
            } else {
              core.setFailed('Forbidden paths changed without maintainer override label or maintainer actor.');
            }
